# Generated by Django 3.0.7 on 2020-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbbusinessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='enderecoComplemento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
